[package]
name = "rinha-backend-rust"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
deadpool-postgres = "0.10"
tokio-postgres = "0.7.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
uuid = { version = "1.4", features = ["v4", "fast-rng"] }
chrono = "0.4"
config = "0.13.3"
reqwest = "0.11"
futures = "0.3"
deadqueue = "0.2"
sql-builder = "3.1"