version: '3.5'

services:
  api01: # API - Instância 01
    image: actixweb:beforeakita
    hostname: api01
    depends_on:
      - db
      - redis
    environment:
      PORT: "8080"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
    network_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  api02: # API - Instância 02
    image: actixweb:beforeakita
    hostname: api02
    depends_on:
      - db
      - redis
    environment:
      PORT: "8081"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
    network_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
    network_mode: "host"

  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: rinhadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'
    network_mode: "host"
  redis:
    image: redis
    hostname: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'
    network_mode: "host"

# networks:
#   default:
#     driver: bridge
#     name: rinha
