version: '3.5'
# Original cpu and mem:
# sum cpus: 2 x 0.15 + 0.14 + 0.9 + 0.15 = 0.59 + 0.9 = 1.49
# sum mem.: 2 x 0.4 + 0.5 + 1.4 + 0.3 = 3GB
services:
  api01: &api
    # image: distanteagle16/rinhabackend:latest
    image: ubuntu-rust-rinha:4
    # build: .
    environment:
      HTTP_PORT: 8080
      DB_HOST: localhost
      REDIS_HOST: localhost
      POOL_SIZE: 30
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
    network_mode: "host"

  api02:
    <<: *api
    environment:
      HTTP_PORT: 8081
      DB_HOST: localhost
      REDIS_HOST: localhost
      POOL_SIZE: 30

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.1GB'

  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.9GB'
